### ISSUE TITLE
Tratar album de mensagens 

### ISSUE THREAD

**Issue by BiancaPereira** [cafeinabots/cafeina-vagas-bot#3]
Issue criada a partir desse PR:
https://github.com/compiladoras/cafeina-vagas-bot/pull/2

Quando o bot de receber vagas recebe um álbum de mensagens, ele não reconhece e dá erro.

Melhoria: ajustar o bot para que ele reconheça o álbum de imagens e sua legenda (caption).

*Aviso*: Se você estiver trabalhando nessa issue, avise nos comentários para que eu te coloque como responsável por essa issue.

Se você não estiver mais atuando nessa issue, é só avisar que eu removo seu nome e outra pessoa comece a atuar nela.

**Comment by alleSilva** [comment]
Olá, gostaria de ajudar com a programação do bot.

**Comment by cafeinabots** [comment]
Verificar se essa issue foi resolvida

**Comment by matricce** [comment]
Pode fechar a issue 😅

**Comment by BiancaPereira** [comment]
Resolvido!
